### PR TITLE
updated style.css

### PR DESCRIPTION
**Pull request by amitesh1as**
with rounded corners and form height and etc.

### CODE REVIEW

**Comment by amitesh1as** [comment]
i hope you accept my pr and further I can also redesign your whole website

**Comment by amitesh1as** [comment]
Please accept my pr

**Comment by saikatXshrey** [comment]
> Please accept my pr

image

first pull down the update then send pr🙂

**Comment by amitesh1as** [comment]
> > Please accept my pr
> 
> image
> 
> first pull down the update then send pr🙂

done now please accept

**Comment by saikatXshrey** [comment]
> > > Please accept my pr
> > 
> > 
> > image
> > first pull down the update then send pr🙂
> 
> done now please accept please sir accept it

done brother✌️😄

**Comment by amitesh1as** [comment]
> > > > Please accept my pr
> > > 
> > > 
> > > image
> > > first pull down the update then send pr🙂
> > 
> > 
> > done now please accept please sir accept it
> 
> done brother✌️😄

Thank you but please also add that hacktoberfest accepted label then only it will be considered
Please

**Pull request merged**
